### ISSUE TITLE
Chrome inspect always starts in debug mode

### ISSUE THREAD

**Issue by yaip** [jkup/ama#14]
Even though I don't have any breakpoints, when I right-click on chrome and select inspect, it always starts in debug mode. How can I get rid of it?

**Comment by jkup** [comment]
If you open the sources panel and look on the right sidebar, do you see *any* breakpoints you can remove?

<img width="585" alt="screen shot 2018-01-23 at 10 38 05 am" src="https://user-images.githubusercontent.com/490294/35293779-9346bf1c-0029-11e8-83b1-b568d3c5a83e.png">

**Comment by yaip** [comment]
Nope. https://www.screencast.com/t/vWceKRdB5UT I just press F8. It's not a show-stopper. Merely annoying.

**Comment by jkup** [comment]
Hey, does your code have that `debugger` line in it? If you have `debugger` anywhere in your JS and DevTools open it will always break on that!
