### ISSUE TITLE
One little known thing about you that'd surprise everybody

### ISSUE THREAD

**Issue by mxstbr** [jkup/ama#3]
:+1:

**Comment by jkup** [comment]
I wasn't always in tech!

I used to be in punk bands, hop trains and hitchhike around the country!

![old picture](https://scontent.xx.fbcdn.net/hphotos-xlp1/v/t1.0-9/1929389_515491953317_7880_n.jpg?oh=447680acb4b9c8f43888bba676f63986&oe=5774735A)

**Comment by mxstbr** [comment]
Hah, that's awesome! :tada: Any songs we can listen to somewhere?
