### ISSUE TITLE
Is The Brand worth it?

### ISSUE THREAD

**Issue by Sequoia** [jkup/ama#4]
Being/trying to be a JS star is hard. Blogging, conferences, podcasts, micro-blogging, micro-conferences... [micro-podcasts](https://www.briefs.fm). Constantly jumping from framework to framework like a pond frog with Restless Leg Syndrome lest you should fall behind. What does it take & is it worth it? What does "worth it" look like to you? There's threeish questions

**Comment by jkup** [comment]
To be honest I go back and forth on this so regularly. I think ultimately the brand is not worth it, but I think a lot of people put in the work for more than just the brand.

I really enjoying reading up on new technologies, speaking at conferences, etc. I don't jus do it to try and be a JS star.. it's honestly what I'd be doing even if no one was paying attention to me!
