### ISSUE TITLE
What Atom packages do you use?

### ISSUE THREAD

**Issue by kellyk** [jkup/ama#9]

**Comment by jkup** [comment]
I always think there are a bunch of cool packages I'm missing but here is my current setup!

## Theme
- UI: Atom Material
- Syntax: Atom Material

## Packages
- atom-beautify
- autocomplete-json
- autocomplete-modules
- file-icons
- language-babel
- linter
- minimap
- pigments

![screen shot 2016-07-09 at 11 16 12 am](https://cloud.githubusercontent.com/assets/490294/16709486/eab298e4-45c6-11e6-8267-43a4e14218b2.png)
